### ISSUE TITLE
Add informations about changelog

### ISSUE THREAD

**Issue by Phyks** [jjk-jacky/kalu#11]
Hi,

Do you think it would be possible to implement in kalu some feedback about the changelog ?

To know directly within the kalu interface what are the modifications in the new version.

I think this can be done either by fetching the changelog (pacman -c option) or by fetching directly the SVN commit messages.

Thanks

**Comment by protist** [comment]
@Phyks If it's helpful, I've written a command-line script to pull a package's changelog from the web page. It's called [paclog](https://github.com/protist/paclog), and is in the AUR under the same name.

**Comment by Phyks** [comment]
Thanks, will have a look at it!
