### ISSUE TITLE
Cant Compile Release 3.0.0 CLI Only

### ISSUE THREAD

**Issue by firegore** [jjk-jacky/kalu#24]
Hello,

i cant compile Kalu 3.0.0 with the --disable-gui option, if you run 'make install' it wants to copy the kalu16.png to the Doc Folder, but this File doesnt exist if you compile CLI Only

**Comment by jjk-jacky** [comment]
Oh yeah, sorry about that. Noticed it a few days ago and hadn't pushed
yet. I just pushed a fix for this on branch next.

Thanks!

**Comment by firegore** [comment]
No Problem, i just used a WorkAround for the kalu-cli Package on AUR.
Just seded the last line from the install-data Hook and here you go, for
now^^


Am 09.01.2015 um 22:25 schrieb Olivier Brunel:
