### ISSUE TITLE
$DISPLAY not exposed

### ISSUE THREAD

**Issue by yan12125** [jjk-jacky/kalu#27]
When I'm updating packages via kalu today, I encounter the following warning messages:
![screenshot_2015-04-18_13-12-21](https://cloud.githubusercontent.com/assets/1937689/7214098/a3ef1b7c-e5cc-11e4-9b5f-ae598aa8b985.png)
Seems $DISPLAY is not exposed.

Environment:
Desktop: XFCE I start it via `startxfce` in tty1

**Comment by jjk-jacky** [comment]
hmm... yeah, there will be no $DISPLAY set indeed, but that's normal.
There's one for kalu, the GUI app running under your account, but the
actual sysupgrade is performed by kalu-dbus, which runs under root and
with a different environment (Basically, it sources /etc/profile from an
empty env).

But I don't see a problem with that, and I would say this is more a
flaw/bug in whatever install scriptlet was run there actually, which
seems to assume $DISPLAY would be set.
What if you'd run `pacman -Syu` from a tty? I imagine you'd get the same
error... It shouldn't assume/expect a running Xorg/$DISPLAY, that's
certainly no requirement to perform a sysupgrade.

**Comment by yan12125** [comment]
Yes, I've encountered the same warnings when upgrading the system without X (tty, ssh, etc.), so I usually upgrade packages with X if possible. I expect kalu to have the same environment as clients under X, but obviously I misunderstood something. It's not an issue now, so closing.
