### ISSUE TITLE
Add autoclose option in System upgrade if no errors occurs

### ISSUE THREAD

**Issue by bosyi** [jjk-jacky/kalu#32]

**Comment by jjk-jacky** [comment]
Hey,

So I've thought about this, and I don't think this would be a good idea.
A system upgrade isn't something to take lightly, I mean one shouldn't
just launch it & forget about it, especially an Arch system.

So I think kalu's updater already goes as far as I'm willing to go, that
is the log can be closed/hidden on start, and stay that way all the way
through should there be nothing "worth interest" (warnings, etc).
Meaning you can start the upgrade, and once completed see the log isn't
there and simply close the window without looking more into it. That's
as far as autoclose as I'm comfortable going -- any further than that
wouldn't feel right to me.

Cheers,
-j
