### ISSUE TITLE
Autohide tray icon

### ISSUE THREAD

**Issue by Generator** [jjk-jacky/kalu#38]
Add ability to hide icon when there's no notifications.  
Useful when have too many tray icons or be minimalist and save space

**Comment by jjk-jacky** [comment]
I don't think this is feasible: kalu doesn't handle the icon itself, as
in showing it or not. You have another application that handles your
systray area, which might decide to show/hide certain icons based on
certain conditions. You might be able to ask for kalu's icon to be
hidden away there, but that's outside of kalu's scope.

As far as kalu goes, the icon needs to always exists, as it is the only
GUI available to interact with.
