### ISSUE TITLE
Untranslatable dropboxes

### ISSUE THREAD

**Issue by AdmiringWorm** [jjk-jacky/kalu#44]
While doing the translation to Norwegian I discovered
a few dropboxes which seems to be not handled at all.
Mainly all dropboxes on the preferences window with the text *Default*/*Fall back*/*Custom* and *None*

Ex: 
![untranslated dropboxes](https://cloud.githubusercontent.com/assets/1474648/13398544/1421fd3e-deff-11e5-84c7-40b38804fe4e.png)

**Comment by jjk-jacky** [comment]
Oops.. right, when redoing the templates UI I did fail to make those
translatable indeed. Just pushed a fix to next.

Thanks!
