### ISSUE TITLE
Message "X not found in AUR" for package wchich is going to be removed during update

### ISSUE THREAD

**Issue by gumik** [jjk-jacky/kalu#48]
It happended to me today when update for xfce4-mixer arrived. This package was replaced by xfce4-pulseaudio but kalu showed message "xfce4-mixer not found in AUR".

Output of pacman -Syu:
```
:: Starting full system upgrade...
:: Replace xfce4-mixer with extra/xfce4-pulseaudio-plugin? [Y/n] 
resolving dependencies...
looking for conflicting packages...

Packages (5) js-24.2.0-4  libkeybinder3-0.3.1-1  polkit-0.113+29+g3272a98-1  xfce4-mixer-4.11.0-3 [removal]  xfce4-pulseaudio-plugin-0.2.4-4

Total Download Size:    2.63 MiB
Total Installed Size:  13.24 MiB
Net Upgrade Size:      11.26 MiB

```

**Comment by jjk-jacky** [comment]
Yes, but that's normal behavior: when kalu did its check, xfce4-mixer
was a package you had on your system, that didn't exist (anymore) in
any repo, so it was checked for in the AUR - and announced missing
there as well.

As your pacman output shows, for the package to be removed you need to
(a) perform a sysupgrade, and (b) accept to replace it w/ a new one
(xfce4-pulseaudio-plugin). Those are possible future events, so they
can't be accounted for by kalu.

**Comment by gumik** [comment]
Please tell me if I understand it correctly. There is no way to know that some packages will be replaced during sysupgrade without doing sysupgrade. Right?
However, message about missing AUR package is confusing. Can this be somehow improved?

**Comment by jjk-jacky** [comment]
Right.

I'm not sure the message is confusing, it means you have a package
installed that isn't in any repo, nor in the AUR. Of course this is a
"special" case where it turns out you'll remove that package, so it's
okay, but that's it.
I don't see how it could be improved, it's a generic title, not
specific to this particular case. (You can always tweak the template if
you want though, in Preferences.)

**Comment by gumik** [comment]
Sounds reasonable. :-)
Thanks for quick response!
