### ISSUE TITLE
Unread news is reset after every reboot

### ISSUE THREAD

**Issue by aaronm-cloudtek** [jjk-jacky/kalu#59]
As per title. I get the same 10 unread news items every time I reboot.

**Comment by jjk-jacky** [comment]
Right, I assume this is actually the bug due to the news title (on Arch
Linux website) beginning with a space; See #57

In which case, a fix has been pushed to branch next. (So e.g.
building kalu-git from the AUR will get you a fixed version.)

**Comment by aaronm-cloudtek** [comment]
Thanks!
