### ISSUE TITLE
Pacman 5.1 breaks kalu's dependency requirement

### ISSUE THREAD

**Issue by kevinselvaprasanna** [jjk-jacky/kalu#62]
Pacman 5.1.0-1 was released yesterday. But I cannot upgrade to it as it breaks kalu's dependency requirement version<5.1. Why is the requirement in place? Is there a fix to it? I get the following error when I try to run `pacman -Syu`
```
error: failed to prepare transaction (could not satisfy dependencies)
:: kalu: installing pacman (5.1.0-1) breaks dependency 'pacman<5.1'
```

**Comment by jjk-jacky** [comment]
- Note that you're talking about the packaging in the AUR, so it doesn't
  really apply here; However...
- The dependency you mention does exist for a reason, the latest
  version of kalu depends on a specific version of pacman (libalpm
  really), and with pacman 5.1 there's a new release of libalpm with
  API changes/breakages & the needed soname bump. 
  The "fix" is to update kalu to make it compile against the new pacman
  (again, libalpm really). I haven't had time yet to look into it, so
  for now you have to chose between pacman 5.1 or kalu.

I'll do my best to try and work on a new release of kalu compatible
with pacman 5.1, but I don't really have an ETA for now...

**Comment by jjk-jacky** [comment]
Okay, if you wanna try things with pacman 5.1 I just pushed a branch
pacman-5.1 which should be compatible; Turns out except for changes in
the download callbacks there wasn't really anything... hopefully I
haven't missed anything :)

Let me know how that works for you,

**Comment by dpeukert** [comment]
Based on my limited testing, everything seems to be working as it should.

**Comment by Fledermann** [comment]
Works nicely so far, thank you.

Here's the q&d pkgbuild I used, to keep everything within pacman.

[PKGBUILD.txt](https://github.com/jjk-jacky/kalu/files/2055566/PKGBUILD.txt)

**Comment by jghodd** [comment]
It now seems to be working as usual. Thanks much.
